"""Compositor-specific window rule generation for gpu-select.

Supports niri, Hyprland, and Sway. Generates snippet files that users
include/source from their compositor config.

Limitations:
- niri: spawn-at-startup entries only apply to apps launched at startup.
  Per-window env var injection is not natively supported by niri's window-rule
  system. The generated snippet covers startup-launched apps only.
- Hyprland: exec rules launch apps on startup; windowrulev2 cannot inject env
  vars at runtime, so per-app GPU switching requires launching via exec.
- Sway: no per-window env var support; exec lines launch apps on startup.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from gpu_select.detect import GPU

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SNIPPET_DIR = Path("~/.config/gpu-select").expanduser()

COMPOSITOR_SNIPPET: dict[str, Path] = {
    "niri": SNIPPET_DIR / "niri.kdl",
    "hyprland": SNIPPET_DIR / "hyprland.conf",
    "sway": SNIPPET_DIR / "sway.conf",
}

COMPOSITOR_CONFIG: dict[str, Path] = {
    "niri": Path("~/.config/niri/config.kdl").expanduser(),
    "hyprland": Path("~/.config/hypr/hyprland.conf").expanduser(),
    "sway": Path("~/.config/sway/config").expanduser(),
}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _env_for_rule(rule: dict, gpus: list[GPU], default_gpu: str) -> dict[str, str]:
    """Return the env-var dict for a rule's target GPU."""
    target: str = rule.get("gpu", default_gpu)
    for gpu in gpus:
        if gpu.label == target or gpu.device == target or gpu.name == target:
            return gpu.env
    # Fall back to default GPU env (may be empty for iGPU)
    for gpu in gpus:
        if gpu.label == default_gpu or gpu.is_default:
            return gpu.env
    return {}


def _env_pairs(env: dict[str, str]) -> list[tuple[str, str]]:
    """Return sorted (key, value) pairs from an env dict."""
    return sorted(env.items())


# ---------------------------------------------------------------------------
# Per-compositor generators
# ---------------------------------------------------------------------------

def _generate_niri(rules: list[dict], default_gpu: str, gpus: list[GPU]) -> str:
    """Generate a niri KDL snippet with spawn-at-startup entries.

    NOTE: niri's window-rule system does not support injecting environment
    variables into running processes.  These entries are only effective for
    apps listed here that niri launches at compositor startup.
    """
    lines: list[str] = [
        "// Generated by gpu-select",
        "// NOTE: niri only supports env vars for spawn-at-startup entries.",
        "// Per-window env injection is not available; only startup apps are covered.",
        "",
    ]
    for rule in rules:
        app: str = rule.get("app", "")
        if not app:
            continue
        env = _env_for_rule(rule, gpus, default_gpu)
        if not env:
            lines.append(f'spawn-at-startup "{app}"')
        else:
            env_args = " ".join(
                f'"{k}={v}"' for k, v in _env_pairs(env)
            )
            lines.append(f'spawn-at-startup "env" {env_args} "{app}"')
    return "\n".join(lines) + "\n"


def _generate_hyprland(rules: list[dict], default_gpu: str, gpus: list[GPU]) -> str:
    """Generate a Hyprland config snippet with exec lines."""
    lines: list[str] = [
        "# Generated by gpu-select",
        "# Source this file from hyprland.conf with:",
        "#   source = ~/.config/gpu-select/hyprland.conf",
        "",
    ]
    for rule in rules:
        app: str = rule.get("app", "")
        if not app:
            continue
        env = _env_for_rule(rule, gpus, default_gpu)
        if not env:
            lines.append(f"exec = {app}")
        else:
            env_prefix = " ".join(f"{k}={v}" for k, v in _env_pairs(env))
            lines.append(f"exec = env {env_prefix} {app}")
    return "\n".join(lines) + "\n"


def _generate_sway(rules: list[dict], default_gpu: str, gpus: list[GPU]) -> str:
    """Generate a Sway config snippet with exec lines."""
    lines: list[str] = [
        "# Generated by gpu-select",
        "# Include this file from ~/.config/sway/config with:",
        "#   include ~/.config/gpu-select/sway.conf",
        "",
    ]
    for rule in rules:
        app: str = rule.get("app", "")
        if not app:
            continue
        env = _env_for_rule(rule, gpus, default_gpu)
        if not env:
            lines.append(f"exec {app}")
        else:
            env_prefix = " ".join(f"{k}={v}" for k, v in _env_pairs(env))
            lines.append(f"exec env {env_prefix} {app}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def detect_compositor() -> str | None:
    """Detect the running compositor from environment variables.

    Checks (in order):
    - ``NIRI_SOCKET``  → "niri"
    - ``HYPRLAND_INSTANCE_SIGNATURE`` → "hyprland"
    - ``SWAYSOCK`` → "sway"
    - ``XDG_CURRENT_DESKTOP`` (case-insensitive substring match)

    Returns the compositor name as a lowercase string, or ``None`` if
    detection fails.
    """
    if os.environ.get("NIRI_SOCKET"):
        return "niri"
    if os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
        return "hyprland"
    if os.environ.get("SWAYSOCK"):
        return "sway"

    xdg = os.environ.get("XDG_CURRENT_DESKTOP", "").lower()
    if "niri" in xdg:
        return "niri"
    if "hyprland" in xdg:
        return "hyprland"
    if "sway" in xdg:
        return "sway"

    return None


def generate_compositor_config(
    compositor: str,
    rules: list[dict],
    default_gpu: str,
    gpus: list[GPU],
) -> Path:
    """Generate a compositor-specific snippet file.

    Parameters
    ----------
    compositor:
        One of ``"niri"``, ``"hyprland"``, or ``"sway"``.
    rules:
        List of rule dicts, each with at least an ``"app"`` key (command to
        launch) and an optional ``"gpu"`` key (GPU label/device/name to use).
    default_gpu:
        Label, device path, or name of the GPU to use when a rule has no
        explicit ``"gpu"`` key.
    gpus:
        List of :class:`~gpu_select.detect.GPU` objects as returned by
        :func:`~gpu_select.detect.detect_gpus`.

    Returns
    -------
    Path
        Absolute path to the generated snippet file.

    Raises
    ------
    ValueError
        If *compositor* is not one of the supported compositors.
    """
    compositor = compositor.lower()
    if compositor not in COMPOSITOR_SNIPPET:
        supported = ", ".join(sorted(COMPOSITOR_SNIPPET))
        raise ValueError(
            f"Unsupported compositor {compositor!r}. "
            f"Supported: {supported}"
        )

    generators = {
        "niri": _generate_niri,
        "hyprland": _generate_hyprland,
        "sway": _generate_sway,
    }

    content = generators[compositor](rules, default_gpu, gpus)
    snippet_path = COMPOSITOR_SNIPPET[compositor]
    snippet_path.parent.mkdir(parents=True, exist_ok=True)
    snippet_path.write_text(content, encoding="utf-8")
    return snippet_path


def generate_all_compositor_configs(
    rules: list[dict],
    default_gpu: str,
    gpus: list[GPU],
) -> dict[str, Path]:
    """Detect the current compositor and generate its snippet file.

    Returns a dict mapping compositor name → generated snippet path.
    Returns an empty dict if no supported compositor is detected.
    """
    compositor = detect_compositor()
    if compositor is None:
        return {}
    path = generate_compositor_config(compositor, rules, default_gpu, gpus)
    return {compositor: path}


def get_source_instruction(compositor: str) -> str:
    """Return the line to add to the compositor's main config to load the snippet.

    Parameters
    ----------
    compositor:
        One of ``"niri"``, ``"hyprland"``, or ``"sway"``.

    Returns
    -------
    str
        A ready-to-paste config line (including a trailing newline).

    Raises
    ------
    ValueError
        If *compositor* is not supported.
    """
    compositor = compositor.lower()
    snippet = COMPOSITOR_SNIPPET.get(compositor)
    if snippet is None:
        supported = ", ".join(sorted(COMPOSITOR_SNIPPET))
        raise ValueError(
            f"Unsupported compositor {compositor!r}. "
            f"Supported: {supported}"
        )

    instructions: dict[str, str] = {
        "niri": (
            f"// Add the following inside your niri config.kdl to include the snippet:\n"
            f"// (niri does not support file inclusion; copy-paste the contents of\n"
            f"//  {snippet}  into your config.kdl manually.)\n"
        ),
        "hyprland": f"source = {snippet}\n",
        "sway": f"include {snippet}\n",
    }
    return instructions[compositor]
