"""Shell config generation for gpu-select.

Generates ~/.config/gpu-select/env.sh with shell functions/aliases that
wrap commands with the appropriate GPU environment variables.
"""

from __future__ import annotations

import fnmatch
import sys
from pathlib import Path

from gpu_select.detect import GPU


_CONFIG_DIR = Path.home() / ".config" / "gpu-select"
_ENV_FILE = _CONFIG_DIR / "env.sh"


def get_shell_config_path() -> Path:
    """Return the path to the generated shell config file."""
    return _ENV_FILE


def get_source_instruction() -> str:
    """Return the line to add to .bashrc/.zshrc to source the generated config."""
    return f'source "{_ENV_FILE}"'


def _is_glob_pattern(pattern: str) -> bool:
    """Return True if the pattern contains glob metacharacters."""
    return any(c in pattern for c in ("*", "?", "[", "]"))


def _find_gpu(gpus: list[GPU], label: str) -> GPU | None:
    """Find a GPU by label ('igpu' or 'dgpu')."""
    for gpu in gpus:
        if gpu.label == label:
            return gpu
    return None


def _env_prefix(env: dict[str, str]) -> str:
    """Format env vars as a shell inline prefix string."""
    return " ".join(f"{k}={v}" for k, v in env.items())


def generate_shell_config(
    rules: list[dict],
    default_gpu: str,
    gpus: list[GPU],
) -> Path:
    """Generate ~/.config/gpu-select/env.sh from the provided rules.

    Args:
        rules: List of rule dicts with 'match', 'gpu', and optional 'env' keys.
        default_gpu: Label of the default GPU ('igpu' or 'dgpu').
        gpus: List of GPU objects from detect.py.

    Returns:
        Path to the generated shell config file.
    """
    lines: list[str] = [
        "# Generated by gpu-select — do not edit manually",
        "# Re-generate with: gpu-select apply",
        "",
    ]

    for rule in rules:
        match: str = rule.get("match", "")
        gpu_label: str = rule.get("gpu", default_gpu)
        rule_env: dict[str, str] = rule.get("env", {})

        if _is_glob_pattern(match):
            print(
                f"[gpu-select] Warning: skipping glob pattern '{match}' — "
                "shell aliases cannot be created for glob patterns. "
                "Use `gpu-select run` instead.",
                file=sys.stderr,
            )
            lines.append(f"# {match} → {gpu_label}")
            lines.append(
                f"# (glob pattern — only works via `gpu-select run {match}`)"
            )
            lines.append("")
            continue

        lines.append(f"# {match} → {gpu_label}")

        if gpu_label == default_gpu:
            lines.append("# (no wrapper needed — igpu is default)" if default_gpu == "igpu" else "# (no wrapper needed — dgpu is default)")
            lines.append("")
            continue

        # Determine env vars: rule-level overrides take precedence, then GPU env
        gpu = _find_gpu(gpus, gpu_label)
        env: dict[str, str] = {}
        if gpu is not None:
            env.update(gpu.env)
        env.update(rule_env)  # rule-level overrides

        if not env:
            lines.append(f"# (no environment variables defined for {gpu_label})")
            lines.append("")
            continue

        prefix = _env_prefix(env)
        lines.append(f"{match}() {{")
        lines.append(f"    {prefix} command {match} \"$@\"")
        lines.append("}")
        lines.append("")

    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    content = "\n".join(lines) + "\n"
    _ENV_FILE.write_text(content, encoding="utf-8")

    return _ENV_FILE
